export const siteConfig = {
  name: "Khoi Tran",
  title: "Computer Science Student & Software Engineer",
  description: "Portfolio of Khoi Tran — CS @ NJIT, full-stack & AI engineer",
  accentColor: "#33eef4",
  secondaryColor: "#42baf1",
  darkColor: "#0a192f",
  phone: "+1 (862) 279-2030",
  heroTaglines: [
    "a Software Engineer",
    "an AI Developer",
    "a Full-Stack Developer",
    "a CS Student @ NJIT",
  ],
  heroDescription:
    "Computer Science student passionate about building full-stack and AI-powered systems that solve real-world problems through cloud, data, and intelligent automation.",
  social: {
    email: "kat46@njit.edu",
    linkedin: "https://linkedin.com/in/khoi-tran310",
    github: "https://github.com/AnhKhoi0310",
    leetcode: "https://leetcode.com/u/khoianh310/",
  },
  aboutMe:
    "Hi, I'm Khoi Tran — a Computer Science student at New Jersey Institute of Technology (expected May 2027) with a minor in Applied Statistics and a 3.8 GPA. I love solving complex problems with code, where logic and creativity meet innovative solutions.\n\nMy experience spans internships at Chubb, InstaHub, and FinBud, plus ML research at NJIT's Computational Neuroanatomy Lab. I've built serverless IoT platforms, insurance AI assistants, RAG chatbots, and neuroimaging analysis tools — sharpening my skills in full-stack development, cloud architecture, and applied AI.\n\nMy ambition is to design sophisticated programs that address real-world challenges and create meaningful impact through technology.",
  skillCategories: [
    {
      name: "Languages",
      skills: [
        "Python",
        "Java",
        "TypeScript",
        "JavaScript",
        "C++",
        "SQL",
        "Solidity",
        "Bash",
        "HTML/CSS",
      ],
    },
    {
      name: "Frameworks",
      skills: [
        "React",
        "Vue.js",
        "Node.js",
        "Express.js",
        "Next.js",
        "Flask",
        "Spring Boot",
        "Spring AI",
        "LangChain",
        "LangChain4j",
        "Redux",
        "Tailwind CSS",
        "D3",
      ],
    },
    {
      name: "Cloud & DevOps",
      skills: [
        "AWS",
        "Azure",
        "Kubernetes",
        "Docker",
        "Temporal",
        "GitHub Actions",
        "Git",
      ],
    },
    {
      name: "Databases & ML",
      skills: [
        "PostgreSQL",
        "MongoDB",
        "MySQL",
        "Redis",
        "Firebase",
        "PyTorch",
        "TensorFlow",
        "scikit-learn",
        "OpenAI",
      ],
    },
  ],
  skills: [
    "Python",
    "Java",
    "TypeScript",
    "JavaScript",
    "C++",
    "SQL",
    "Solidity",
    "Bash",
    "React",
    "Vue.js",
    "Node.js",
    "Express.js",
    "Next.js",
    "Flask",
    "Spring Boot",
    "Spring AI",
    "LangChain",
    "LangChain4j",
    "Redux",
    "Tailwind CSS",
    "D3",
    "AWS",
    "Azure",
    "Kubernetes",
    "Docker",
    "Temporal",
    "PostgreSQL",
    "MongoDB",
    "MySQL",
    "Redis",
    "Firebase",
    "PyTorch",
    "TensorFlow",
    "scikit-learn",
    "OpenAI",
    "Git",
    "GitHub Actions",
    "Hardhat",
    "Brownie",
  ],
  projects: [
    {
      name: "CPA Agent Bot",
      description:
        "Improved internal support productivity with a TypeScript/Express + Flask RAG platform using Hugging Face embeddings and Azure AI Search, delivering 2–3s responses across 2,000+ indexed document chunks and supporting 50+ authenticated sessions.",
      link: "https://github.com/AnhKhoi0310/CPA_RAG_Agent",
      skills: [
        "TypeScript",
        "Express",
        "Flask",
        "Azure AI Search",
        "Gemini",
        "Docker",
        "Google OAuth",
      ],
    },
    {
      name: "Graph Theoretical Analysis of Task-related Functional Dynamics (GAT-FD)",
      description:
        "Graph Theoretical Analysis of Task-related Functional Dynamics (GAT-FD) is a systematically integrated user-friendly toolkit to characterize the functional dynamics for task-related fMRI data based on graph theoretical techniques and sliding-window-based methods.",
      link: "https://github.com/AnhKhoi0310/GAT_FD",
      skills: [
        "Python",
        "PyTorch",
        "Graph Theory",
        "Neuroimaging",
      ],
    },
    {
      name: "LLM-powered ChartMaker",
      description:
        "Expanded self-serve analytics throughput with a TypeScript/React + Express + Python platform using OpenAI and containerized sandbox execution, supporting 20+ concurrent users with isolated sessions and automated multi-chart generation workflows.",
      link: "https://github.com/AnhKhoi0310/ChartMaker",
      skills: [
        "TypeScript",
        "React",
        "Express",
        "Python",
        "Docker",
        "OpenAI",
        "Kubernetes",
        "Heroku",
      ],
    },
  ],
  experience: [
    {
      company: "Chubb",
      title: "Software Engineer Intern",
      dateRange: "June 2025 - Aug 2025",
      bullets: [
        "Improved enterprise AI workflow reliability by operationalizing Spring Boot microservices on Azure Kubernetes Service with Temporal orchestration, enabling stable execution across 5 production-grade agent flows.",
        "Boosted backend efficiency by 75% through a MongoDB aggregation-first data layer (26 endpoints streamlined to 6 services), reducing round trips and increasing response consistency.",
        "Reduced manual analysis effort by 50% with a LangChain4j + Voyage AI semantic recommendation layer that improved retrieval quality for policy and industry context.",
        "Lowered user-perceived latency by 4–5 seconds via SSE streaming and asynchronous persistence, improving responsiveness for high-interaction assistant sessions.",
      ],
    },
    {
      company: "InstaHub",
      title: "Full Stack Software Engineer Intern",
      dateRange: "May 2025 - Aug 2025",
      bullets: [
        "Increased real-time IoT processing scale with a React + AWS Lambda/API Gateway/RDS serverless stack, supporting 1,000+ sensor events per day while cutting anomaly-detection latency by 30%.",
        "Improved deployment and operations quality across 50+ sensors through centralized metadata management, reducing setup time by 40% and strengthening data consistency.",
        "Raised analytics responsiveness by 25% through Node.js service optimization and query tuning across occupancy and heatmap pipelines.",
        "Reduced historical reporting query time by 35% in PostgreSQL via indexing and data-access optimization, improving dashboard usability for repeated analysis workloads.",
      ],
    },
    {
      company: "FinBud",
      title: "Software Developer",
      dateRange: "May 2025 - Aug 2025",
      bullets: [
        "Expanded intelligent finance coverage using Vue.js, Express.js, MongoDB, and AWS Lambda, sustaining 2,000+ market/news fetches per week for personalized user insights.",
        "Improved market-data freshness and engagement through serverless ingestion on Lambda + API Gateway, enabling near real-time stock and crypto dashboard updates.",
        "Increased release quality by 40% with GitHub Actions CI/CD automation for build, test, and deployment workflows across backend services.",
        "Strengthened platform reliability by pushing automated test coverage to 85% with Jest/Mocha, reducing regression risk during rapid iteration.",
      ],
    },
    {
      company: "Computational Neuroanatomy and Neuroinformatics Lab, NJIT",
      title: "Research Assistant — ML & Neuroimaging Tools",
      dateRange: "Jan 2025 - May 2025",
      bullets: [
        "Improved research analysis throughput with a Python neuroimaging toolbox integrating SPM, Brain Connectivity Toolbox, and PyTorch over 1,101 pediatric ADHD MRI scans.",
        "Reduced end-to-end processing time by 45% through multi-core parallel computation, enabling faster iteration on large-scale neuroimaging experiments.",
      ],
    },
    {
      company: "Manipal Institute of Technology",
      title: "Research Assistant - Blockchain Manipal, India",
      dateRange: "Jul. 2024 - Aug. 2024",
      bullets: [
        "Increased IoT security research reliability by 10% through a blockchain-enabled architecture powered by Python automation and Web3 integration.",
        "Improved trust and traceability on Ethereum Sepolia with Solidity smart contracts, strengthening secure coordination across 3 interconnected IoT devices.",
        "Elevated access-control robustness through ECC and attribute-based authorization patterns, reducing exposure in multi-device communication paths.",
        "Raised confidence in lightweight security validation by integrating ML-assisted interval criteria, improving decision consistency versus baseline approaches.",
      ],
    },
  ],
  education: [
    {
      school: "New Jersey Institute of Technology",
      degree:
        "Bachelor of Science in Computer Science, Minor in Applied Statistics",
      dateRange: "Expected May 2027",
      achievements: [
        "Cumulative GPA: 3.8/4.0",
        "NJIT Dean's List (2024, 2026)",
        "NJIT Academic Scholar Award (2023)",
        "NJIT Highlander Scholarship (2023)",
        "Coursework: Advanced Data Structures and Algorithm Design, Object-Oriented Programming, Data Mining, Computer Networks, Linear Algebra, Intensive Programming, Probability and Statistics",
        "Activities: Google Developer Student Clubs, NJIT Information & Cybersecurity, NJIT Association for Computing Machinery",
      ],
    },
  ],
};
